/*
SQLyog Ultimate v13.1.1 (64 bit)
MySQL - 10.4.17-MariaDB : Database - db_artikel
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`db_artikel` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;

USE `db_artikel`;

/*Table structure for table `tbl_artikel` */

DROP TABLE IF EXISTS `tbl_artikel`;

CREATE TABLE `tbl_artikel` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `judul` varchar(200) DEFAULT NULL,
  `konten` text DEFAULT NULL,
  `tanggal` date DEFAULT NULL,
  `penulis` varchar(100) DEFAULT NULL,
  `slug` text DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb4;

/*Data for the table `tbl_artikel` */

insert  into `tbl_artikel`(`id`,`judul`,`konten`,`tanggal`,`penulis`,`slug`) values 
(1,'Noise - Veteran','Generasi yang kolot bilang gua keparat, Gaya hidup mereka sudah usang dan berkarat, Tapi peduli amat, mereka semua sekarat, Panggil polisi, panggil aja semua aparat (mati) Seperti Arian gua menolak tua\r\nGa cuma ikut ikut seperti kakak tua\r\nYang tua, yang mapan, yang kaya, yang tampan\r\nSemua mencibir karena gua veteran\r\nMereka juga bilang gua ini terlalu kiri\r\nMungkin karena gaya gua terlalu Gosha Rubchinskiy\r\nAtau emang bagi mereka sukses itu ukuran harta\r\nSoalnya kalo beli mobil ga bisa bayar pake pahala\r\nLantas sekarang harga minyak dunia juga udah turun\r\nMereka semua pada panik, emang dasar mental culun\r\nNawarin diri sana sini, cari kerja udah kayak pecun\r\nGiliran susah baru inget Tuhan, langsung sujud minta ampun\r\nAstaghfirullah! Kok susah banget cari kerja?!\r\nTenang aja kalo ga kerja bisa cari beasiswa\r\nOK, mari semuanya langsung daftar LPDP\r\nJalan-jalan ke luar negeri tapi cuma bayar DP\r\nGelar master anda itu sudah basi\r\nBuang buang tenaga seperti masturbasi\r\n24 belum nikah muka langsung pucat pasi\r\nSiapa suruh punya CV tapi bukan punya visi?','2021-05-05','Asvarizal Filcha','noise---veteran'),
(2,'Hindia - Secukupnya','Kapan terakhir kali kamu dapat tertidur tenang?(Renggang) \'Tak perlu memikirkan tentang apa yang akan datang Di esok hari Tubuh yang berpatah hati Bergantung pada gaji Berlomba jadi asri Mengais validasi Dan akupun terhadir Seakan paling mahir Menenangkan dirimu yang merasa terpinggirkan dunia \'Tak pernah adil','2021-05-04','Budi','hindia---secukupnya'),
(3,'Naif - Jikalau','Jikalau telah datang waktu yang dinanti\r\n\'Ku pasti bahagiakan dirimu seorang\r\nKuharap dikau sabar menunggu\r\nBerilah daku waktu \'tuk wujudkan semua\r\nJanji ini untukmu, \'ku tak akan lupa\r\nKuharap dikau sabar menunggu\r\n\'Ku pasti akan datang untukmu','2021-05-03','Dedi','naif---jikalau'),
(4,'Hindia - Untuk Apa / Untuk Apa?','Rumah ini dahulu sederhana\r\nRuang demi ruang dibangun bersama\r\nAngan-angan yang dulu mimpi belaka\r\nKita gapai segala yang tak disangka\r\n\r\nTak sadar menimbun yang lebih berharga\r\nBerdiri di atas yang lebih bermakna\r\nAnak tangga yang berlebihan jumlahnya\r\nMendaki terus entah mau ke mana?\r\n\r\nDan kau selalu bertanya, untuk apa?\r\nMengelak, kerap kutemukan jawabnya\r\nMedusa dan semakin keras kepala\r\nSeakan hidup hanya untuk bekerja\r\n\r\nMengejar mimpi sampai tak punya rasa\r\nMengejar mimpi sampai lupa keluarga\r\nMengejar mimpi lupa dunia nyata\r\nMengejar mimpi tapi tidak bersama\r\n\r\nPadahal katanya uang takkan kemana\r\nJika memang rezeki ya \'kan ditransfer juga\r\nNamun dikejar terus seakan satwa langka\r\nDi prosesnya melintah lupa jadi manusia\r\n\r\nMelihat Hawa jadi panas lupa cuaca\r\nTertiup angin buah jatuh digigit juga\r\nSeakan perlu banyak seperti Dewa Siwa\r\nPadahal manusia hanya bertangan dua\r\n\r\nKasur yang luas tapi bangun sendiri\r\nMobil baru mengkilap tanpa penumpang di kiri\r\nBanyak sepatu minim privasi susah pergi\r\nPS4, nintendo switch tanpa player dua\r\n\r\nDan dahulu kau bertanya, untuk apa?\r\nLalu kuperhatikan ini semua\r\nBarang mahal yang tidak ada harganya\r\nDan sekarang, ku bertanya untuk apa?\r\n\r\nTerlepas apa yang engkau percayai\r\nTetap takkan ada yang dibawa mati\r\nKembali ke tanah dan tumbuh cemara\r\nMana saja harta yang lebih berharga\r\n\r\nTerlepas apa yang engkau percayai\r\nTetap takkan ada yang dibawa mati\r\nKembali ke tanah dan tumbuh cemara\r\nMana saja harta yang lebih berharga\r\n\r\nTerlepas apa yang engkau percayai\r\nTetap takkan ada yang dibawa mati\r\nMenimbun surga yang tak bisa dibagi\r\nAkhirnya pun wafat sendiri-sendiri\r\n\r\nMengangkat ikat rambutmu yang tertinggal\r\nDi lengan kiri mobilku, terakhir kita menonton\r\nJariku tak juga kuat, sungguh janggal\r\nLebih berat dari seribu ton\r\n\r\nSatu dari ribuan hal kecil\r\nYang sekarang menjadi terampil\r\nMenggosok garam di atas luka\r\nDulu tak ada apa-apanya\r\n\r\nRute pagi yang dahulu ceria\r\nMenu favorit kini hambar rasanya\r\nFoto yang tak berani dilirik mata\r\nKontak sekarang jadi sebatas nama\r\n\r\nMasing-masing selamat dan bercerita\r\nNamun tidak lagi miliki bersama\r\n\r\nCepat namun sendiri, untuk apa?\r\nBersama tapi meracuni, untuk apa?','2021-05-02','Asvarizal Filcha','hindia---untuk-apa-/-untuk-apa?'),
(5,'Hindia - Evaluasi','Yang tak bisa terobati\r\nBiarlah\r\nMengering sendiri\r\nMenghias tubuh dan\r\nYang mengevaluasi\r\nRagamu\r\nHanya kau sendiri\r\nMereka tak mampu\r\nMelewati yang telah kau lewati\r\nTiap berganti hari\r\nRintangan yang kau hadapi\r\nMasalah yang mengeruh\r\nHo, perasaan yang rapuh\r\nIni belum separuhnya\r\nBiasa saja\r\nKamu tak apa\r\nYang selalu ingin ambil peran\r\nHanya berlomba menjadi lebih\r\nSedih dari dirimu\r\nMuak dikesampingkan\r\nDisamakan\r\nHatimu terluka, sempurna\r\nMasalah yang mengeruh\r\nHo, perasaan yang rapuh\r\nIni belum separuhnya\r\nBiasa saja\r\nKamu tak apa\r\nPerjalanan yang jauh\r\nKau bangun untuk bertaruh\r\nHari belum selesai\r\nBiasa saja\r\nKamu tak apa\r\nBilas muka, gosok gigi, evaluasi\r\nTidur sejenak menemui esok pagi\r\nWalau pedihku bersamamu kali ini\r\nKu masih ingin melihatmu esok hari\r\nBilas muka, gosok gigi, evaluasi\r\nTidur sejenak menemui esok pagi\r\nWalau pedihku bersamamu kali ini\r\nKu masih ingin melihatmu esok hari\r\nBilas muka, gosok gigi, evaluasi\r\nTidur sejenak menemui esok pagi\r\nWalau pedihku bersamamu kali ini\r\nKu masih ingin melihatmu esok hari','2021-05-01','Asvarizal Filcha','hindia---evaluasi'),
(6,'Goodnight Electric - Rocket Ship Goes By','I remember when you said\r\nWe have come from outside world\r\nFull of grass and only love\r\nSleeping, eating so full of joy\r\nYou are something new\r\nAnd suddenly appear\r\nAm I caught in bigger picture or\r\nAm I trapped in paralyzed mind of you?\r\nWhen I listen to this song\r\nThat\'s connected by its parts\r\nStimulated trough the heart\r\nIt\'s only you that I regard\r\nBaby I should not have believed it\r\nBut, oh no I sink and dream it\r\nIt\'s so foolish and it\'s a joy\r\nI would never be restored\r\nYeah, I put my trust on me\r\nNot on you not even this world\r\nTo see the truth, oh yeah, oh no\r\nThey only saw it on TV\r\nAnd I almost believe it\r\nAll the promises you\'ve made\r\nJust to set up the gasoline\r\nThat you gave to me\r\nIt can\'t be real\r\nAnd now it\'s time for the rocket ship goes by (Five)\r\nI knew it\'s broken (Four)\r\nBut I made it fly (Three)\r\nI\'m sorry baby (Two)\r\nI\'ve got a good home (One)\r\nUntil we have to say goodbye (Launch)','2021-05-01','Asvarizal Filcha','goodnight-electric---rocket-ship-goes-by'),
(7,'Daun Jatuh - Antara Pagi Dan Kau','Pagi ini mentari bersinar cerah\r\nNamun cerahnya tak secerah parasmu\r\nPagi ini burung berkicau nan merdu\r\nNamun tak semerdu saat kau menyapaku\r\nDengan tulus dan penuh keyakinan\r\nKutitipkan segala yang kupunya padamu\r\nAku ingin kau selalu ada di sini\r\n\'Tuk temani hari yang terus berganti\r\nKarena aku tak pernah mau \'tuk sendiri\r\nRaga dan jiwaku nyaman bersamamu\r\nPagi ini bunga bermekaran manis\r\nNamun tak semanis saat kau menatapku\r\nDengan tulus dan penuh keyakinan\r\nKutitipkan segala yang kupunya padamu\r\nAku ingin kau selalu ada di sini\r\n\'Tuk temani hari yang terus berganti\r\nKarena aku tak pernah mau \'tuk sendiri\r\nRaga dan jiwaku nyaman bersamamu\r\nJangan pernah kau pergi\r\nTinggalkan \'ku sendiri\r\nJangan membuatku tertatih\r\nKarena luka yang perih\r\nJangan pernah kau pergi\r\nTinggalkan \'ku sendiri\r\nJangan membuatku tertatih\r\nKarena luka yang perih\r\nLagi\r\nAku ingin kau selalu ada di sini\r\n\'Tuk temani hari yang terus berganti\r\nKarena aku tak pernah mau \'tuk sendiri\r\nRaga dan jiwaku nyaman bersamamu','2021-05-01','Asvarizal Filcha','daun-jatuh---antara-pagi-dan-kau'),
(8,'Figura Renata - Rasa Dan Karsa','Dan waktu ku tak lama\r\nSemoga bisa bermakna\r\nUntuk semesta\r\nTua\r\nRenta\r\nSenja\r\nSisa perih jemari\r\nMendamba hujan\r\nKala Oktober\r\nMasih tersisa jua\r\nRasa pelupuk lara\r\nLara...\r\nLara...\r\nAa-aa\r\nWarna makna tercipta\r\nSisipkan harap dan doa\r\nWarna makna tercipta\r\nSisipkan harap dan doa\r\nWarna makna tercipta\r\nSisipkan harap dan doa\r\nWarna makna tercipta\r\nSisipkan harap dan doa\r\nWarna makna tercipta\r\nSisipkan harap dan doa\r\nWarna…','2021-05-01','Asvarizal Filcha','figura-renata---rasa-dan-karsa'),
(9,'Pamungkas - Sorry','Sometimes I can\'t be on my own\r\nOr else I\'ll think too much again\r\nAnd it\'s about what I did wrong\r\nTimes like this I wish you\'re here with me\r\nOh yeah\r\nFor all the things I didn\'t do\r\nAnd all the love that I haven\'t got to you\r\nI\'m sorry\r\nI wish I could turn back the time\r\nAnd let you know, I never meant to hurt you\r\nI\'m sorry\r\nI\'m sorry\r\nI miss us when I\'m on my own\r\nOh, now I feel too much again\r\nIt\'s plain and cold after you\'re gone\r\nTimes like this I wish you\'re here with me\r\nOh yeah\r\nAnd hold me\r\nAnd hold me\r\nFor all the things I didn\'t do\r\nAnd all the love that I haven\'t got to you\r\nI\'m sorry\r\nI wish I could turn back the time\r\nAnd let you know, I never meant to hurt you\r\nI\'m sorry\r\nI\'m sorry\r\nFor all the things I didn\'t say\r\nAnd all the times I wasn\'t there with you\r\nI\'m sorry\r\nI know I couldn\'t turn back the time\r\nAnd let you know, I never meant to hurt you\r\nSo I\'m sorry\r\n(I\'m sorry)','2021-05-01','Asvarizal Filcha','pamungkas---sorry'),
(10,'Nadin Amizah - Sorai','Langit dan laut saling membantu\r\nMencipta awan, hujan pun turun\r\nKetika dunia saling membantu\r\nLihat, cinta mana yang tak jadi satu\r\n\r\nKau memang manusia sedikit kata\r\nBolehkah aku yang berbicara?\r\nKau memang manusia tak kasat rasa\r\nBiar aku yang mengemban cinta\r\n\r\nAwan dan alam saling bersentuh\r\nMencipta hangat, kau pun tersenyum\r\nKetika itu kulihat syahdu\r\nLihat, hati mana yang tak akan jatuh\r\n\r\nKau memang manusia sedikit kata\r\nBolehkah aku yang berbicara\r\nKau memang manusia tak kasat rasa\r\nBiar aku yang mengemban cinta\r\n\r\nKau dan aku saling membantu\r\nMembasuh hati yang pernah pilu\r\nMungkin akhirnya tak jadi satu\r\nNamun bersorai pernah bertemu','2021-05-01','Asvarizal Filcha','nadin-amizah---sorai'),
(11,'Fletch - Tiga Pagi','Dalam diam\r\nAda luka\r\nYang tertawa riang\r\nDan\r\nHening yang menangis\r\nTerlalu dalam\r\nDalam diam\r\nAda luka\r\nYang tertawa riang\r\nDan\r\nHening yang menangis\r\nTerlalu dalam\r\nRibuan cahaya\r\nHilangkan gelap\r\nMenatapmu\r\nTak kuasa\r\nKu terserap\r\nKamu meredup\r\nAku tak hidup\r\nKamu meredup\r\nAku tak hidup\r\nKamu meredup\r\nDan aku\r\nTak hidup','2021-05-01','Asvarizal Filcha','fletch---tiga-pagi'),
(12,'Senja - Perih','Waktu perlahan menuntunku\r\nBerjumpa lagi denganmu\r\nSeseorang yang dulu bersamaku\r\nTakdir tak ingin kita bersatu\r\nKini kau bersamanya\r\nTak ada ruang untukku di hatimu\r\nTerlambat kusesali semua yang terjadi\r\nDi saat kutahu kau tak mungkin kembali\r\nTak kusangka sedalam ini kuterluka\r\nKarena cinta yang kuingkari\r\nTakdir tak ingin kita bersatu\r\nKini kau bersamanya\r\nTak ada ruang untukku di hatimu\r\nTerlambat kusesali semua yang terjadi\r\nDi saat kutahu kau tak mungkin kembali\r\nTak kusangka sedalam ini kuterluka\r\nKarena cinta yang kuingkari\r\nAndai saja aku bisa merubah sang waktu\r\nTak akan pernah kuberpaling meninggalkanmu\r\nMencoba sekuat hatiku merelakanmu dengannya\r\nMeski \'ku takkan bisa','2021-05-01','Asvarizal Filcha','senja---perih'),
(13,'Sisir Tanah - Lagu Pejalan','Siapakah kita ini, manusia\r\nYang dalam diam, riuh, ragu, dan tak mampu\r\nAda rahasia, tidak rahasia\r\nAda di sini ada di situ\r\nDiseret-seret waktu\r\nKita berjalan saja masih,\r\nTerus berjalan\r\nMeskipun kita tak tau\r\nB\'rapa jauh, jalan ini nanti\r\nDan kita tak juga rela tunduk\r\nPada jarak\r\nDan kita tak juga rela tunduk\r\nPada jarak\r\nKita berjalan saja masih,\r\nS\'lalu berjalan\r\nMeskipun kita tak kunjung tau ujung jalan ini\r\nDan kita tak juga kan terhenti\r\nS\'lalu berjalan\r\nDan kita tak juga kan terhenti\r\nS\'lalu berjalan\r\nBertahankah kita ini, manusia\r\nYang dalam riang, ringkih, rumit, dan terhimpit\r\nAda bahagia, tidak bahagia\r\nAda di sini ada di sana\r\nDitikam-tikam rasa\r\nKita berjalan saja masih,\r\nTerus berjalan\r\nMeskipun kita tak tau, b\'rapa jauh, jalan ini nanti\r\nDan kita tak juga rela tunduk\r\nPada jarak\r\nDan kita tak juga rela tunduk pada jarak\r\nKita berjalan saja masih\r\nS\'lalu berjalan\r\nMeskipun kita tak kunjung, tau ujung jalan ini\r\nDan kita tak juga kan terhenti, s\'lalu berjalan\r\nDan kita tak juga kan terhenti, s\'lalu berjalan','2021-05-01','Asvarizal Filcha','sisir-tanah---lagu-pejalan'),
(14,'Hindi - Rumah ke Rumah','Menyesal, tak kusampaikan\r\nCinta monyetku ke Kanya dan Rebecca\r\nApa kabar kalian di sana?\r\nSemoga hidup baik-baik saja\r\nTak belajar, terkena getahnya\r\nSaat bersama Thanya dan Saphira\r\nKupercaya mungkin bukan jalannya\r\nNamun kalian banyak salah juga\r\nJika dahulu ku tak cepat berubah\r\nIni maafku untukmu, Sharfina\r\nSegala doa yang baik adanya\r\nUntukmu dan mimpimu yang mulia\r\nPindah berkala, rumah ke rumah\r\nBerharap bisa berujung indah\r\nWalau akhirnya harus berpisah\r\nTerima kasih karena ku tak mudah\r\nPindah berkala, rumah ke rumah\r\nBerharap bisa berujung indah\r\nWalau akhirnya harus berpisah\r\nTerima kasih karena ku tak mudah\r\nMaaf jika kusering buat susah\r\nIndisya, Panda, Anggra, Caca, Sismita\r\nPerempuan terkuat dalam hidupku\r\nTerjanglah apa pun yang kalian tuju\r\nKau datang saat gelapku merekah\r\nSeluruh hatiku untukmu, Meidiana\r\nKau pantas dapatkan yang baik di dunia\r\nSemoga kita bertahan lama\r\nPindah berkala, rumah ke rumah\r\nMengambil pelajaran jika berpisah\r\nJikalau suatu saat berujung indah\r\nCatat nama kita dalam sejarah\r\nPindah berkala, rumah ke rumah\r\nMengambil pelajaran jika berpisah\r\nJikalau suatu saat berujung indah\r\nCatat nama kita dalam sejarah\r\nLetih mengembara, rumah ke rumah\r\nKadang kulupa akanmu, Amalia\r\nSiap sedia tiap kubercerita\r\nKuberuntung jadi anakmu, Bunda\r\nPindah berkala, rumah ke rumah\r\nSelalu pada dirimu aku berserah\r\nJika aku disebut dalam sejarah\r\nMereka takkan lupa karena siapa\r\nPindah berkala, rumah ke rumah\r\nSelalu pada dirimu aku berserah\r\nJika aku disebut dalam sejarah\r\nMereka takkan lupa karena siapa','2021-05-01','Asvarizal Filcha','hindi---rumah-ke-rumah'),
(15,'Kunto Aji - Rehat','Serat-serat harapan\r\nMasih terjalin suaramu terdengar\r\nMasihlah nyaring dan bergema\r\nDi ruang-ruang hatimu\r\nTenangkan hati\r\nSemua ini bukan salahmu\r\nJangan berhenti\r\nYang kau takutkan takkan terjadi\r\nYang dicari hilang\r\nYang dikejar lari\r\nYang ditunggu\r\nYang diharap\r\nBiarkanlah semesta bekerja\r\nUntukmu\r\nTenangkan hati\r\nSemua ini bukan salahmu\r\nJangan berhenti\r\nYang kau takutkan takkan terjadi\r\nKita coba lagi\r\nUntuk lain hari\r\nKita coba lagi\r\nYang ditunggu\r\nYang diharap\r\nBiarkanlah semesta bekerja\r\nUntukmu\r\nTenangkan hati\r\nSemua ini bukan salahmu\r\nTerus berlari\r\nYang kau takutkan takkan terjadi','2021-05-01','Asvarizal Filcha','kunto-aji---rehat'),
(16,'Chrisye - Seperti Yang Kau Minta','Maafkan aku tak bisa memahami maksud amarahmu\r\nMembaca dan mengerti isi hatimu\r\nAmpuni aku yg telah memasuki kehidupan kalian\r\nMencoba mencari celah dalam hatimu\r\nAku tau ku takkan bisa menjadi seperti yg engkau minta\r\nNamun selama nafas berhembus aku kan mencoba menjadi seperti yg kau minta\r\nAmpuni aku yg telah memasuki kehidupan kalian\r\nMencoba mencari celah dalam hatimu\r\nAku tau ku takkan bisa menjadi seperti yg engkau minta\r\nNamun selama nafas berhembus aku kan mencoba\r\nAku tau dia yg bisa menjadi seperti yg engkau minta\r\nNamun selama aku bernyawa aku kan mencoba menjadi seperti yg kau minta\r\nAku tau ku takkan bisa menjadi seperti yg engkau minta\r\nNamun selama nafas berhembus aku kan mencoba\r\nAku tau dia yg bisa menjadi seperti yg engkau minta\r\nNamun selama aku bernyawa aku kan mencoba menjadi seperti yg kau minta\r\nSeperti yg kau minta, aku kan mencoba menjadi seperti yg kau minta','2021-05-01','Asvarizal Filcha','chrisye---seperti-yang-kau-minta'),
(17,'Laluna - Selepas Kau Pergi','Selepas kau pergi\r\nTinggalah disini kusendiri\r\nKumerasakan sesuatu\r\nYang tlah hilang didalam hidupku\r\nDalam lubuk hatimu\r\nKu yakin kau pun sebenarnya\r\nTak inginkan lepas dariku\r\nTahukah kau kini ku terluka\r\nBantu aku membencimu\r\nKu terlalu mencintaimu\r\nDirimu begitu berarti untukku\r\nKau telah mencinta\r\nDan dicintai kekasihmu\r\nIni tak adil bagiku\r\nHilanglah damba tinggalah hampa\r\nBantu aku membencimu\r\nKu terlalu mencintaimu\r\nDirimu begitu berarti untukku\r\nBantu aku membencimu\r\nKu terlalu mencintaimu\r\nDirimu begitu berarti untukku\r\nLupakanku dalam hidupmu\r\nYang pernah mencintaimu\r\nKau memang tercipta bukanlah untukku\r\nSelepas kau pergi\r\nTinggalah disini kusendiri\r\nKumerasakan sesuatu\r\nYang tlah hilang didalam hidupku','2021-05-01','Asvarizal Filcha','laluna---selepas-kau-pergi'),
(18,'Jikustik - Saat Kau Tak Disini','Seperti bintang-bintang\r\nHilang ditelan malam\r\nBagai harus melangkah\r\nTanpa kutahu arah\r\nLepaskan aku dari\r\nDerita tak bertepi\r\nSaat kau tak disini\r\nSeperti dedaunan\r\nBerjatuhan di taman\r\nBagaikan debur ombak\r\nMampu pecahkan karang\r\nLepaskan aku dari\r\nDerita tak berakhir\r\nSaat kau tak ada disini\r\nSaat kau tak ada\r\nAtau kau tak disini\r\nTerpenjara sepi\r\nKunikmati sendiri\r\nTak terhitung waktu\r\nTuk melupakanmu\r\nAku tak pernah bisa\r\nAku tak pernah bisa oh\r\nSeperti dedaunan\r\nBerjatuhan di taman\r\nBagaikan debur ombak\r\nMampu pecahkan karang\r\nLepaskan aku dari\r\nDerita tak berakhir\r\nSaat kau tak ada disini\r\nSaat kau tak ada\r\nAtau kau tak disini\r\nTerpenjara sepi\r\nKunikmati sendiri\r\nTak terhitung waktu\r\nTuk melupakanmu\r\nAku tak pernah bisa\r\nAku tak pernah bisa oh oh oh\r\nSaat kau tak ada\r\nAtau kau tak disini\r\nTerpenjara sepi\r\nKunikmati sendiri\r\nTak terhitung waktu\r\nTuk melupakanmu\r\nAku tak pernah bisa\r\nAku tak pernah bisa\r\nSaat kau tak ada\r\nAtau kau tak disini\r\nTerpenjara sepi\r\nKunikmati sendiri\r\nTak terhitung waktu\r\nTuk melupakanmu\r\nAku tak pernah bisa\r\nAku tak pernah bisa oh\r\nSeperti bintang bintang\r\nHilang di telan malam','2021-05-01','Asvarizal Filcha','jikustik---saat-kau-tak-disini'),
(19,'Chrisye - Kala Cinta Menggoda','Sejak jumpa kita pertama, kulangsung jatuh cinta\r\nWalau kutahu kau ada pemiliknya\r\nTapi \'ku tak dapat membohongi hati nurani\r\n\'Ku tak dapat menghindari gejolak cinta ini\r\nMaka izinkanlah aku mencintaimu\r\nAtau bolehkanlah aku sekadar sayang padamu\r\nMaka izinkanlah aku mencintaimu\r\nAtau bolehkanlah aku sekadar sayang padamu\r\nMemang serba salah rasanya tertusuk panah cinta\r\nApalagi aku juga ada pemiliknya\r\nTapi \'ku tak mampu membohongi hati nurani\r\n\'Ku tak mampu menghindari gejolak cinta ini\r\nMaka maafkan jika aku mencintaimu\r\nAtau biarkan \'ku mengharap kau sayang padaku\r\nMaka maafkan jika aku mencintaimu\r\nAtau biarkan \'ku mengharap kau sayang padaku\r\n(Lorone loro\r\nOra koyo wong kang nandang wuyung\r\nMangan ra doyan\r\nRa jenak dolan, nang ngomah bingung)\r\nTapi \'ku tak dapat membohongi hati nurani\r\n\'Ku tak mampu menghindari gejolak cinta ini\r\nMaka izinkanlah aku mencintaimu\r\nAtau bolehkanlah aku sekadar sayang padamu\r\nMaka maafkan jika aku mencintaimu\r\nAtau biarkan \'ku mengharap kau sayang padaku\r\nMaka izinkanlah aku mencintaimu\r\nAtau bolehkanlah aku sekadar sayang padamu\r\nMaka maafkan jika aku mencintaimu\r\nAtau biarkan \'ku mengharap kau sayang padaku','2021-05-01','Asvarizal Filcha','chrisye---kala-cinta-menggoda'),
(20,'Pamungkas - Monolog','Gelap, di dalam tanya\r\nMenyembunyikan rahasianya\r\nLetih kehabisan kata\r\nDan kita pada akhirnya diam\r\nBunga, di bulan sepi\r\nJatuh terdampar\r\nTersasar\r\nAlasan masih bersama\r\nBukan karena terlanjur lama\r\nTapi rasanya yang masih sama\r\nSeperti sejak pertama jumpa\r\nDirimu di kala senja\r\nDuduk berdua tanpa suara\r\nRindu yang jatuh di kamarku\r\nHanyalah rindu yang datang padamu\r\nBertanya mengapa kita\r\nMasih di sini tersenyum\r\nYeah\r\nAlasan masih bersama\r\nBukan karena terlanjur lama\r\nTapi rasanya yang masih sama\r\nSeperti sejak pertama jumpa\r\nDirimu di kala senja\r\nDuduk berdua tanpa suara','2021-05-01','Asvarizal Filcha','pamungkas---monolog');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
